"""empty message

Revision ID: 92a9ddcf35a2
Revises: 4b7229a46ada
Create Date: 2020-03-28 22:04:50.210930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92a9ddcf35a2'
down_revision = '4b7229a46ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_refresh_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('previous_refresh', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('last_refresh_time')
    # ### end Alembic commands ###
