"""empty message

Revision ID: a0dcb87035b1
Revises: 92a9ddcf35a2
Create Date: 2020-03-29 21:22:10.097591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0dcb87035b1'
down_revision = '92a9ddcf35a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('last_refresh_time')
    op.add_column('users', sa.Column('dev_access', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('prod_access', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'prod_access')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'dev_access')
    op.create_table('last_refresh_time',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('previous_refresh', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='last_refresh_time_pkey')
    )
    op.drop_table('configs')
    # ### end Alembic commands ###
